 // Code generated by golem/dicts/cmd/generate_pack.go DO NOT EDIT
package fr

import "github.com/aaaton/golem/dicts"

const locale = "fr"

// LanguagePack is an implementation of the generic golem.LanguagePack interface for fr
type LanguagePack struct {
}

// NewPackage creates a language pack
func New() dicts.LanguagePack {
	return &LanguagePack{}
}

// GetResource returns the dictionary of lemmatized words
func (l *LanguagePack) GetResource() ([]byte, error) {
	return Asset("data/" + locale + ".gob")
}

// GetLocale returns the language name
func (l *LanguagePack) GetLocale() string {
	return locale
}

